name: twilight_foodz_customer
description: "Working and developed mobile app for Twilight Foodz"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.5
  jwt_decoder: ^2.0.1
  http: ^1.6.0
  google_phone_number_hint: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: "^0.14.4"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/lotties/
    - lib/assets/icons/